### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by ghost** [ericelliott/cuid#40] opened 2015-08-20 17:14 UTC
I could  being doing something really stupid (as is the case normally) but I can't get my tests to pass in Node with cuid.

``` bash
error trying to resolve DateInputViewModel navigator is not defined ReferenceError: navigator is not d
efined
```

If I dig a little further, it looks like cuid is expecting the `window.navigator` to exist... but obviously this is not the case when running in a Node process. I am using Testem's launchers to run this particular suite of tests, and perhaps that is where the error lies. Maybe Testem isn't setting an environment variable correctly and therefore some kind of `cuid` check of `if process.env === node` is failing?

Any ideas would be appreciated.

**Comment by ericelliott** [comment] 2015-08-20 23:47
What version are you using? Are you sure it's cuid causing the error?

The node version of cuid shouldn't give you any trouble with browser stuff.

**Comment by aft-luke** [comment] 2015-08-20 23:51
`"cuid": "^1.2.4"` and node `v0.12.7`... I'll double check again where the error is coming from.

**Comment by ericelliott** [comment] 2015-08-20 23:54
The latest version of cuid is 1.2.5. Try that, first.

**Comment by aft-luke** [comment] 2015-08-24 17:39
1.2.5 Didn't resolve the problem, either. Maybe something else is conflating what's really going on. I'm trying to run tests via `mochajs` - and that's where the `navigator is not defined` error's are coming from. This is expected, since node processes don't have a window.navigator - but I thought `cuid` supported node and browsers... which is what makes me think something is tricking `cuid` into believing it's actually inside a browser.

**Comment by ericelliott** [comment] 2015-08-24 23:17
Interesting. It looks to me like the server version isn't even getting built. @therealklanni

**Comment by ericelliott** [comment] 2015-08-25 12:15
I strongly suspect this is related to [issue 42](https://github.com/ericelliott/cuid/issues/42). Does the current version work for you?

**Comment by aft-luke** [comment] 2015-08-25 13:15
It doesn't, but the issue may very well still be on my end. I'm thinking the problem is that when running browserify to compact all the `**/tests/*-spec.js` the environment is node set to `--node`, which means your `package.json "browser": "/dist/browser-cuid.js"` is getting pulled in instead. Bummer.

**Comment by therealklanni** [comment] 2015-08-26 00:59
@ericelliott looking into it. This was working before, might be related to the recent changes, trying to nail it down.

In short, the "navigator is not defined" is caused by the fact that node doesn't have a concept of a navigator, so for tests to run they need to be run in a browser, not in node.

**Comment by ericelliott** [comment] 2015-08-26 01:34
@therealklanni Yeah, but in a Node build, the `"main"` module should be used, not the `"browser"` version. The browser version should only be pulled in for browserify / webpack builds targeting browsers. AFAIK, this is configured correctly in our `package.json`, so I'm a little puzzled about why this is happening.

Here's an ugly workaround in the meantime: specify the exact path/filename to import the correct package instead of `import cuid from 'cuid';`.

**Comment by therealklanni** [comment] 2015-08-26 18:39
I think this is related to #42. I believe once we finish resolving that issue it will shed some light on this.

**Comment by jdoleary** [comment] 2017-08-13 16:29
I just ran into this issue trying to use the new node debugger built into Chrome Dev Tools

**Comment by ericelliott** [comment] 2017-08-14 03:21
If you want to try to get resolve the build/CI test failures in [this PR](https://github.com/ericelliott/cuid/pull/72) it should solve this issue.

**Closed** 2017-09-06 04:55 UTC
